In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
df = pd.read_excel('hours_examscore_data.xlsx')
df.head()

   Hours_Studied  Exam_Score
0           0.20        43.4
1           0.21        41.8
2           0.27        30.4
3           0.30        35.8
4           0.39        35.1

In [8]:
df.describe()

       Hours_Studied  Exam_Score
count     100.000000   99.000000
mean        5.033900   66.129293
std         2.966425   18.604604
min         0.200000   30.400000
25%         2.145000   51.250000
50%         5.740000   70.000000
75%         7.745000   81.850000
max         9.720000  100.000000